    - name: Install lxml
      pip: name=lxml
      
    - name: remove war file from temp folder
      shell: rm -rf /tmp/hello-world-maven.war
  
    - name: "Download war file from Nexus"
      maven_artifact:
       group_id: io.happycoding
       artifact_id: hello-world-maven
       extension: war
       version: '{{ version }}' 
       repository_url: "http://18.181.205.133:8081/repository/maven-releases/"
       username: "{{ username }}"
       password: "{{ password }}"
       dest: "/tmp/hello-world-maven.war"
       mode: '0644'

  #  - name: Execute the command in remote shell; stdout goes to the specified file on the remote
  #    ansible.builtin.shell: amazon-linux-extras install java-openjdk11 -y

    - name: download tomcat server packages
      get_url:
       url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
       dest: /usr/local

    - name: extract tomcat packages
      unarchive:
       src: /usr/local/apache-tomcat-10.0.27.tar.gz
       dest: /usr/local
       remote_src: yes

    - name: Copy the war file
      copy:
       src: /tmp/hello-world-maven.war
       dest: /usr/local/apache-tomcat-10.0.27/webapps/
       remote_src: yes
       
    - name: changing tomcat port number
      template:
       src: /var/lib/jenkins/workspace/FirstPipeline/server.xml.j2
       dest: /usr/local/apache-tomcat-10.0.27/conf/server.xml
       mode: '0777'
      listen: "Stop tomcat services"
      listen: "Start Tomcat"  
       
#    - name:  Stop Tomcat
#      command: echo "This task will stop tomcat services"
#      notify: "Stop tomcat services"
      
#    - name:  Start Tomcat
#      command: echo "This task will start tomcat services"
#      notify: "Start Tomcat"  
      
      
       
#   handlers:
#    - name: Stop tomcat services
#      shell: /usr/local/apache-tomcat-10.0.27/bin/shutdown.sh

 #   - name: Start Tomcat
 #     shell: nohup /usr/local/apache-tomcat-10.0.27/bin/startup.sh
