---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: ijaz21/helloworldmaven_0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
              name: http
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8090
  type: LoadBalancer
  selector:
    app: my-app

